--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Codename-Aurora/DisableDrops
branches:
- master
projects:
  DisableDrops:
    path: "https://image.flaticon.com/icons/svg/1276/1276834.svg"
...
